export const sharedObjects = {
  // List of other ingredients that can be added to a recipe via dropdown selection
  otherIngredients: [
    {
      value: "bakers_non_fat_dry_milk",
      description: "Baker's Non-Fat Dry Milk",
      ratio: 0.1375661,
      key: "o1",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "baking_powder",
      description: "Baking Powder",
      ratio: 0.1410934,
      key: "o2",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "baking_soda",
      description: "Baking Soda",
      ratio: 0.1410934,
      key: "o3",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "butter_margarine",
      description: "Butter/Margarine",
      ratio: 0.1668136,
      key: "o4",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "buttermilk,_dry",
      description: "Buttermilk, dry",
      ratio: 0.0705467,
      key: "o5",
      note: "Recommended 4.0 - 6.0%",
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "buttermilk,_fresh_lowfat",
      description: "Buttermilk, fresh (lowfat)",
      ratio: 0.1800411,
      key: "o6",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "canola_oil",
      description: "Canola Oil",
      ratio: 0.1601998,
      key: "o7",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "citric_acid",
      description: "Citric Acid",
      ratio: 0.17636995,
      key: "o39",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "clarified_butter_ghee",
      description: "Clarified Butter (Ghee)",
      ratio: 0.1506466,
      key: "o8",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "corn_flour",
      description: "Corn Flour",
      ratio: 0.0852439,
      key: "o9",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "corn_oil",
      description: "Corn Oil",
      ratio: 0.1587301,
      key: "o10",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "corn_syrup",
      description: "Corn Syrup",
      ratio: 0.2398098,
      key: "o11",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "cornmeal",
      description: "Cornmeal",
      ratio: 0.116843,
      key: "o12",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "cream_of_tartar",
      description: "Cream of Tartar",
      ratio: 0.1058201,
      key: "o13",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "diastatic_milk_powder",
      description: "Diastatic Malt Powder",
      ratio: 0.0881834,
      key: "o14",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "dry_non_fat_milk_carnations",
      description: "Dry Non-Fat Milk (Carnation's)",
      ratio: 0.0507054,
      key: "o15",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "egg_whites_fresh,_raw",
      description: "Egg Whites (fresh, raw)",
      ratio: 0.1785714,
      key: "o16",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "eggs_large,_fresh,_raw",
      description: "Eggs (large, fresh, raw)",
      ratio: 0.1785714,
      key: "o17",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "honey",
      description: "Honey",
      ratio: 0.2466666,
      key: "o18",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "lard",
      description: "Lard",
      ratio: 0.1528512,
      key: "o19",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "malted_milk_powder_carnations",
      description: "Malted Milk Powder (Carnation's)",
      ratio: 0.0823045,
      key: "o20",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "maple_syrup_pure",
      description: "Maple Syrup (pure)",
      ratio: 0.2366255,
      key: "o21",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "milk_fresh",
      description: "Milk (fresh)",
      ratio: 0.1763668,
      key: "o22",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "molasses",
      description: "Molasses",
      ratio: 0.2443415,
      key: "o23",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "non_diastatic_barley_malt_syrup",
      description: "Non-Diastatic Barley Malt Syrup",
      ratio: 0.2469135,
      key: "o24",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "olive_oil",
      description: "Olive Oil",
      ratio: 0.1587301,
      key: "o25",
      note: "Typical: 1.5",
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "potatoflour",
      description: "Potato Flour",
      ratio: 0.134039,
      key: "o26",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "riceflour",
      description: "Rice Flour",
      ratio: 0.0881849,
      key: "o39",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "wholewheat",
      description: "White Whole Wheat",
      ratio: 0.0881849,
      key: "o40",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "whitewholewheat",
      description: "Whole Wheat",
      ratio: 0.0881849,
      key: "o41",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "pz_44",
      description: "PZ-44",
      ratio: 0.083333,
      key: "o27",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "rye_flour",
      description: "Rye Flour",
      ratio: 0.0813247,
      key: "o28",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "semolina",
      description: "Semolina",
      ratio: 0.1227219,
      key: "o29",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "shortening",
      description: "Shortening",
      ratio: 0.140934,
      key: "o30",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "soy_flour",
      description: "Soy Flour",
      ratio: 0.0705467,
      key: "o31",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "sugar",
      description: "Sugar",
      ratio: 0.140625,
      key: "o32",
      note: "Typical: 1",
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "sweet_dried_dairy_whey",
      description: "Sweet Dried Dairy Whey",
      ratio: 0.1065549,
      key: "o33",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "vegetable_soybean_oil",
      description: "Vegetable (Soybean) Oil",
      ratio: 0.1601998,
      key: "o34",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "vinegar",
      description: "Vinegar",
      ratio: 0.1763668,
      key: "o35",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "vital_wheat_gluten",
      description: "Vital Wheat Gluten",
      ratio: 0.0975896,
      key: "o36",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "wrise",
      description: "WRISE",
      ratio: 0.1834215,
      key: "o37",
      note: null,
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "yellow_food_coloring",
      description: "Yellow Food Coloring",
      ratio: 0.1975308,
      key: "o38",

      note: null,
      dropsInTsp: 90,
      amount: null,
    },
  ],

  // Other ingredients that are applied to a recipe by default
  defaultAddedIngredients: [
    {
      value: "olive_oil",
      description: "Olive Oil",
      ratio: 0.1587301,
      key: "o25",
      note: "Typical: 1.5",
      dropsInTsp: null,
      amount: 1.5,
    },
    {
      value: "sugar",
      description: "Sugar",
      ratio: 0.140625,
      key: "o32",
      note: "Typical: 1",
      dropsInTsp: null,
      amount: 1.0,
    },
  ],

  // Same as above but with 0 amounts
  resetAddedIngredients: [
    {
      value: "olive_oil",
      description: "Olive Oil",
      ratio: 0.1587301,
      key: "o25",
      note: "Typical: 1.5",
      dropsInTsp: null,
      amount: null,
    },
    {
      value: "sugar",
      description: "Sugar",
      ratio: 0.140625,
      key: "o32",
      note: "Typical: 1",
      dropsInTsp: null,
      amount: null,
    },
  ],

  defaultTableConfig: {
    show: {
      grams: true,
      kilograms: false,
      milliliters: false,
      ounces: false,
      pounds: false,
      teaspoons: false,
      tablespoons: false,
      cups: false,
      drops: false,
      title: true,
      notes: true,
    },
    precision: 1,
    precisionString: "1.0-3",
  },

  // ...
};
